---
version: '3.8'

services:
  cryptpad:
    image: "promasu/cryptpad:nginx"
    hostname: cryptpad
    environment:
      - CPAD_MAIN_DOMAIN=crypt.web4.zone
      - CPAD_SANDBOX_DOMAIN=sandbox.gtfo.web4.zone
      # Traefik can't use HTTP2 to communicate with cryptpad_websocket
      # ... http upgrade that ws might help plebs
      # nvm using c4ddy 4now
      # A workaround is to disable HTTP2 in Nginx (muh srsly)
      - CPAD_HTTP2_DISABLE=true

    volumes:
      - ./data/blob:/cryptpad/blob
      - ./data/block:/cryptpad/block
      - ./customize:/cryptpad/customize
      - ./data/data:/cryptpad/data
      - ./data/files:/cryptpad/datastore
      - ./data/config.js:/cryptpad/config/config.js

    ports:
      - "780:80"
      - "7443:443"
    expose:
      - "780"
      - "7443"

    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
